language: c
script: make test
branches:
  only:
    - gh-pages
notifications:
  irc:
    channels:
      - "chat.freenode.net#selenium"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{commit}): %{message}"
      - "Build details: %{build_url}"
sudo: false
